name: CI

on:
  push:
    branches: [ dev/* ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git
        uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev
          #pipenv run python setup.py install
          
      - name: Run linters
        run: |
          pipenv run mypy ./src
          pipenv run pytype ./src
      
      - name: Run tests
        run: pipenv run python -m pytest
