---
name: Upload
on:
  workflow_dispatch: # manual trigger
  release:
    types: [created]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git
        uses: actions/checkout@v6
      - name: Install UV
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.9
          enable-cache: true
      - name: Install dependencies
        run: |
          uv sync --locked --dev
      - name: Build package
        run: |
          uv build
      - name: Publish package
        if: startsWith(github.ref, 'refs/tags')
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: uv publish
